development:
  adapter: postgresql
  encoding: unicode
  database: smartcoding_development
  pool: 5
  timeout: 5000
  username: sergeylukin
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: smartcoding_test
  pool: 5
  timeout: 5000
  username: sergeylukin
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: smartcoding_production
  pool: 5
  timeout: 5000
  username: smartcoding
  password: 123456
